import type { Gender, Availability } from "../src/generated/prisma/client";

export type ExpansionVariantSpec = {
  color: string;
  size: string;
  availability?: Availability;
  price?: number;
};

export type ExpansionProductSpec = {
  externalId: string;
  brand: string;
  categorySlug: string;
  name: string;
  description: string;
  price: number;
  gender: Gender;
  productUrl: string;
  variants: ExpansionVariantSpec[];
  attributes: Record<string, string>;
};

const BRAND_DOMAINS: Record<string, string> = {
  Nike: "nike.com",
  Adidas: "adidas.com",
  Puma: "puma.com",
  Zara: "zara.com",
  "H&M": "hm.com",
  "New Balance": "newbalance.com",
};

export function buildProductUrl(
  brand: string,
  externalId: string
): string {
  const domain =
    BRAND_DOMAINS[brand] ?? "example.com";
  return `https://www.${domain}/p/${externalId}`;
}

type SpecInput = {
  ext: string;
  brand: string;
  cat: string;
  name: string;
  desc: string;
  price: number;
  gender: Gender;
  colors: string[];
  sizes: string[];
  attrs: Record<string, string>;
  oosColors?: string[];
};

function spec(input: SpecInput): ExpansionProductSpec {
  const oos = new Set(
    input.oosColors ?? []
  );

  return {
    externalId: input.ext,
    brand: input.brand,
    categorySlug: input.cat,
    name: input.name,
    description: input.desc,
    price: input.price,
    gender: input.gender,
    productUrl: buildProductUrl(
      input.brand,
      input.ext
    ),
    variants: input.colors.flatMap((color) =>
      input.sizes.map((size) => ({
        color,
        size,
        availability:
          oos.has(color)
            ? ("OUT_OF_STOCK" as Availability)
            : ("AVAILABLE" as Availability),
      }))
    ),
    attributes: input.attrs,
  };
}

const SOLID_TOP = {
  Collar: "Round Neck",
  Pattern: "Solid",
};

export const expansionProducts: ExpansionProductSpec[] =
  [
    /* ---------- POLOS (6) ---------- */
    spec({
      ext: "exp-polo-grey-001",
      brand: "Puma",
      cat: "polos",
      name: "Grey Essential Polo",
      desc: "Grey cotton polo with classic collar.",
      price: 34.99,
      gender: "MEN",
      colors: ["Grey"],
      sizes: ["M", "L"],
      attrs: {
        ...SOLID_TOP,
        Collar: "Polo",
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Casual",
        Material: "Cotton",
      },
    }),
    spec({
      ext: "exp-polo-navy-001",
      brand: "Nike",
      cat: "polos",
      name: "Men Navy Performance Polo",
      desc: "Moisture-wicking performance polo.",
      price: 44.99,
      gender: "MEN",
      colors: ["Blue"],
      sizes: ["S", "M", "XL"],
      attrs: {
        ...SOLID_TOP,
        Collar: "Polo",
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
      },
    }),
    spec({
      ext: "exp-polo-white-001",
      brand: "H&M",
      cat: "polos",
      name: "White Slim Polo",
      desc: "White slim fit cotton polo.",
      price: 24.99,
      gender: "MEN",
      colors: ["White"],
      sizes: ["M"],
      attrs: {
        ...SOLID_TOP,
        Collar: "Polo",
        Sleeve: "Short Sleeve",
        Fit: "Slim",
        Style: "Casual",
        Material: "Cotton",
      },
    }),
    spec({
      ext: "exp-polo-green-001",
      brand: "Zara",
      cat: "polos",
      name: "Green Pique Polo",
      desc: "Green pique polo for men.",
      price: 29.99,
      gender: "MEN",
      colors: ["Green"],
      sizes: ["L", "XL"],
      attrs: {
        ...SOLID_TOP,
        Collar: "Polo",
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Classic",
        Material: "Cotton",
      },
    }),
    spec({
      ext: "exp-polo-red-001",
      brand: "Adidas",
      cat: "polos",
      name: "Red Sport Polo",
      desc: "Red athletic polo shirt.",
      price: 39.99,
      gender: "UNISEX",
      colors: ["Red"],
      sizes: ["M", "L"],
      attrs: {
        ...SOLID_TOP,
        Collar: "Polo",
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
      },
    }),
    spec({
      ext: "exp-polo-black-001",
      brand: "New Balance",
      cat: "polos",
      name: "Black Golf Polo",
      desc: "Black lightweight golf polo.",
      price: 49.99,
      gender: "MEN",
      colors: ["Black"],
      sizes: ["S", "M"],
      attrs: {
        ...SOLID_TOP,
        Collar: "Polo",
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
      },
    }),

    /* ---------- BLOUSES (6) ---------- */
    spec({
      ext: "exp-blouse-white-001",
      brand: "Zara",
      cat: "blouses",
      name: "White Satin Blouse",
      desc: "Elegant white satin blouse.",
      price: 39.99,
      gender: "WOMEN",
      colors: ["White"],
      sizes: ["XS", "S"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "V-Neck",
        Fit: "Regular",
        Style: "Formal",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-blouse-blue-001",
      brand: "H&M",
      cat: "blouses",
      name: "Blue Striped Blouse",
      desc: "Blue striped office blouse.",
      price: 29.99,
      gender: "WOMEN",
      colors: ["Blue"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "Round Neck",
        Fit: "Regular",
        Style: "Formal",
        Material: "Cotton",
        Pattern: "Striped",
      },
    }),
    spec({
      ext: "exp-blouse-red-001",
      brand: "Zara",
      cat: "blouses",
      name: "Women Red Silk Blouse",
      desc: "Red silk blouse for women.",
      price: 49.99,
      gender: "WOMEN",
      colors: ["Red"],
      sizes: ["XS", "S", "M"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "V-Neck",
        Fit: "Slim",
        Style: "Formal",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-blouse-black-001",
      brand: "H&M",
      cat: "blouses",
      name: "Black Chiffon Blouse",
      desc: "Lightweight black chiffon blouse.",
      price: 27.99,
      gender: "WOMEN",
      colors: ["Black"],
      sizes: ["S"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "Round Neck",
        Fit: "Regular",
        Style: "Casual",
        Material: "Synthetic",
        Pattern: "Solid",
      },
      oosColors: ["Black"],
    }),
    spec({
      ext: "exp-blouse-green-001",
      brand: "Zara",
      cat: "blouses",
      name: "Green Linen Blouse",
      desc: "Breathable green linen blouse.",
      price: 34.99,
      gender: "WOMEN",
      colors: ["Green"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "Short Sleeve",
        Collar: "V-Neck",
        Fit: "Regular",
        Style: "Casual",
        Material: "Linen",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-blouse-grey-001",
      brand: "H&M",
      cat: "blouses",
      name: "Grey Checked Blouse",
      desc: "Grey checked blouse for women.",
      price: 25.99,
      gender: "WOMEN",
      colors: ["Grey"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "Round Neck",
        Fit: "Regular",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Checked",
      },
    }),

    /* ---------- CARDIGANS (5) ---------- */
    spec({
      ext: "exp-cardi-beige-grey-001",
      brand: "H&M",
      cat: "cardigans",
      name: "Grey Wool Cardigan",
      desc: "Soft grey wool cardigan.",
      price: 49.99,
      gender: "WOMEN",
      colors: ["Grey"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "V-Neck",
        Fit: "Regular",
        Style: "Casual",
        Material: "Wool",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-cardi-black-001",
      brand: "Zara",
      cat: "cardigans",
      name: "Black Knit Cardigan",
      desc: "Black knit cardigan for women.",
      price: 45.99,
      gender: "WOMEN",
      colors: ["Black"],
      sizes: ["XS", "S"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "V-Neck",
        Fit: "Slim",
        Style: "Casual",
        Material: "Wool",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-cardi-red-001",
      brand: "H&M",
      cat: "cardigans",
      name: "Red Oversized Cardigan",
      desc: "Red oversized knit cardigan.",
      price: 42.99,
      gender: "WOMEN",
      colors: ["Red"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "Round Neck",
        Fit: "Oversized",
        Style: "Casual",
        Material: "Wool",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-cardi-green-001",
      brand: "Zara",
      cat: "cardigans",
      name: "Green Button Cardigan",
      desc: "Green button-up cardigan.",
      price: 39.99,
      gender: "WOMEN",
      colors: ["Green"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "V-Neck",
        Fit: "Regular",
        Style: "Classic",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-cardi-white-001",
      brand: "H&M",
      cat: "cardigans",
      name: "White Cropped Cardigan",
      desc: "White cropped cardigan for women.",
      price: 34.99,
      gender: "WOMEN",
      colors: ["White"],
      sizes: ["XS", "S"],
      attrs: {
        Sleeve: "Long Sleeve",
        Collar: "Round Neck",
        Fit: "Slim",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),

    /* ---------- EXTRA T-SHIRTS (4) ---------- */
    spec({
      ext: "exp-tshirt-black-men-001",
      brand: "Nike",
      cat: "t-shirts",
      name: "Men Black Training T-Shirt",
      desc: "Black dry-fit training t-shirt for men.",
      price: 32.99,
      gender: "MEN",
      colors: ["Black"],
      sizes: ["M", "L", "XL"],
      attrs: {
        ...SOLID_TOP,
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
      },
    }),
    spec({
      ext: "exp-tshirt-grey-001",
      brand: "Adidas",
      cat: "t-shirts",
      name: "Grey Everyday T-Shirt",
      desc: "Grey cotton everyday t-shirt.",
      price: 22.99,
      gender: "UNISEX",
      colors: ["Grey"],
      sizes: ["S", "M", "L"],
      attrs: {
        ...SOLID_TOP,
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Casual",
        Material: "Cotton",
      },
    }),
    spec({
      ext: "exp-tshirt-red-001",
      brand: "Puma",
      cat: "t-shirts",
      name: "Red Logo T-Shirt",
      desc: "Red t-shirt with small logo.",
      price: 24.99,
      gender: "MEN",
      colors: ["Red"],
      sizes: ["M"],
      attrs: {
        ...SOLID_TOP,
        Sleeve: "Short Sleeve",
        Fit: "Regular",
        Style: "Casual",
        Material: "Cotton",
      },
    }),
    spec({
      ext: "exp-tshirt-women-green-001",
      brand: "H&M",
      cat: "t-shirts",
      name: "Women Green Basic T-Shirt",
      desc: "Green basic t-shirt for women.",
      price: 17.99,
      gender: "WOMEN",
      colors: ["Green"],
      sizes: ["XS", "S"],
      attrs: {
        ...SOLID_TOP,
        Sleeve: "Short Sleeve",
        Fit: "Slim",
        Style: "Casual",
        Material: "Cotton",
      },
    }),

    /* ---------- EXTRA TANK TOPS (3) ---------- */
    spec({
      ext: "exp-tank-white-001",
      brand: "Nike",
      cat: "tank-tops",
      name: "White Performance Tank Top",
      desc: "White breathable training tank.",
      price: 27.99,
      gender: "UNISEX",
      colors: ["White"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "Sleeveless",
        Collar: "Round Neck",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-tank-grey-001",
      brand: "Adidas",
      cat: "tank-tops",
      name: "Grey Gym Tank Top",
      desc: "Grey lightweight gym tank top.",
      price: 24.99,
      gender: "MEN",
      colors: ["Grey"],
      sizes: ["M"],
      attrs: {
        Sleeve: "Sleeveless",
        Collar: "Round Neck",
        Fit: "Slim",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-tank-women-red-001",
      brand: "Zara",
      cat: "tank-tops",
      name: "Women Red Ribbed Tank Top",
      desc: "Red ribbed tank top for women.",
      price: 18.99,
      gender: "WOMEN",
      colors: ["Red"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "Sleeveless",
        Collar: "Round Neck",
        Fit: "Slim",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),

    /* ---------- CHINOS (6) ---------- */
    spec({
      ext: "exp-chino-beige-001",
      brand: "Zara",
      cat: "chinos",
      name: "Beige Slim Chinos",
      desc: "Beige slim fit chinos for men.",
      price: 45.99,
      gender: "MEN",
      colors: ["Brown"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-chino-navy-001",
      brand: "H&M",
      cat: "chinos",
      name: "Navy Classic Chinos",
      desc: "Navy blue classic chinos.",
      price: 39.99,
      gender: "MEN",
      colors: ["Blue"],
      sizes: ["M", "L", "XL"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Classic",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-chino-green-001",
      brand: "Zara",
      cat: "chinos",
      name: "Green Utility Chinos",
      desc: "Green utility-style chinos.",
      price: 49.99,
      gender: "MEN",
      colors: ["Green"],
      sizes: ["L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-chino-women-white-001",
      brand: "Zara",
      cat: "chinos",
      name: "Women White Chinos",
      desc: "White chinos for women.",
      price: 42.99,
      gender: "WOMEN",
      colors: ["White"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-chino-grey-001",
      brand: "H&M",
      cat: "chinos",
      name: "Grey Stretch Chinos",
      desc: "Grey stretch fabric chinos.",
      price: 36.99,
      gender: "MEN",
      colors: ["Grey"],
      sizes: ["M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Straight",
        Style: "Casual",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-chino-black-001",
      brand: "Zara",
      cat: "chinos",
      name: "Black Smart Chinos",
      desc: "Black smart-casual chinos.",
      price: 47.99,
      gender: "UNISEX",
      colors: ["Black"],
      sizes: ["S", "M", "L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Formal",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),

    /* ---------- TROUSERS (5) ---------- */
    spec({
      ext: "exp-trouser-black-001",
      brand: "H&M",
      cat: "trousers",
      name: "Black Formal Trousers",
      desc: "Black formal trousers for men.",
      price: 54.99,
      gender: "MEN",
      colors: ["Black"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Formal",
        Material: "Wool",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-trouser-grey-001",
      brand: "Zara",
      cat: "trousers",
      name: "Grey Pleated Trousers",
      desc: "Grey pleated tailored trousers.",
      price: 59.99,
      gender: "WOMEN",
      colors: ["Grey"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Formal",
        Material: "Wool",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-trouser-blue-001",
      brand: "H&M",
      cat: "trousers",
      name: "Blue Relaxed Trousers",
      desc: "Blue relaxed fit trousers.",
      price: 44.99,
      gender: "UNISEX",
      colors: ["Blue"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Oversized",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-trouser-brown-001",
      brand: "Zara",
      cat: "trousers",
      name: "Brown Corduroy Trousers",
      desc: "Brown corduroy trousers.",
      price: 52.99,
      gender: "MEN",
      colors: ["Brown"],
      sizes: ["L", "XL"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Straight",
        Style: "Classic",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-trouser-white-001",
      brand: "H&M",
      cat: "trousers",
      name: "White Linen Trousers",
      desc: "White linen summer trousers.",
      price: 46.99,
      gender: "WOMEN",
      colors: ["White"],
      sizes: ["XS", "S"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Linen",
        Pattern: "Solid",
      },
    }),

    /* ---------- LEGGINGS (5) ---------- */
    spec({
      ext: "exp-legging-black-001",
      brand: "Nike",
      cat: "leggings",
      name: "Black Training Leggings",
      desc: "Black high-waist training leggings.",
      price: 34.99,
      gender: "WOMEN",
      colors: ["Black"],
      sizes: ["XS", "S", "M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-legging-grey-001",
      brand: "Adidas",
      cat: "leggings",
      name: "Grey Sports Leggings",
      desc: "Grey melange sports leggings.",
      price: 29.99,
      gender: "WOMEN",
      colors: ["Grey"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-legging-green-001",
      brand: "H&M",
      cat: "leggings",
      name: "Green Yoga Leggings",
      desc: "Green yoga leggings for women.",
      price: 24.99,
      gender: "WOMEN",
      colors: ["Green"],
      sizes: ["S"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
      oosColors: ["Green"],
    }),
    spec({
      ext: "exp-legging-blue-001",
      brand: "Puma",
      cat: "leggings",
      name: "Blue Running Leggings",
      desc: "Blue running leggings with pocket.",
      price: 32.99,
      gender: "WOMEN",
      colors: ["Blue"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-legging-red-001",
      brand: "Nike",
      cat: "leggings",
      name: "Red Compression Leggings",
      desc: "Red compression sport leggings.",
      price: 37.99,
      gender: "WOMEN",
      colors: ["Red"],
      sizes: ["XS", "S"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),

    /* ---------- JOGGERS (5) ---------- */
    spec({
      ext: "exp-jogger-black-001",
      brand: "Nike",
      cat: "joggers",
      name: "Black Fleece Joggers",
      desc: "Black fleece-lined joggers.",
      price: 44.99,
      gender: "UNISEX",
      colors: ["Black"],
      sizes: ["S", "M", "L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-jogger-grey-001",
      brand: "Adidas",
      cat: "joggers",
      name: "Grey Lounge Joggers",
      desc: "Grey comfortable lounge joggers.",
      price: 34.99,
      gender: "UNISEX",
      colors: ["Grey"],
      sizes: ["M", "XL"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-jogger-blue-001",
      brand: "Puma",
      cat: "joggers",
      name: "Blue Track Joggers",
      desc: "Blue track-style joggers.",
      price: 39.99,
      gender: "MEN",
      colors: ["Blue"],
      sizes: ["L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-jogger-women-green-001",
      brand: "H&M",
      cat: "joggers",
      name: "Women Green Joggers",
      desc: "Green joggers for women.",
      price: 29.99,
      gender: "WOMEN",
      colors: ["Green"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Slim",
        Style: "Casual",
        Material: "Cotton",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-jogger-red-001",
      brand: "New Balance",
      cat: "joggers",
      name: "Red Sport Joggers",
      desc: "Red sporty joggers with zip pockets.",
      price: 42.99,
      gender: "MEN",
      colors: ["Red"],
      sizes: ["M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),

    /* ---------- EXTRA JEANS (3) ---------- */
    spec({
      ext: "exp-jeans-black-001",
      brand: "Zara",
      cat: "jeans",
      name: "Black Skinny Jeans",
      desc: "Black skinny fit jeans.",
      price: 43.99,
      gender: "MEN",
      colors: ["Black"],
      sizes: ["M", "L"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Skinny",
        Style: "Casual",
        Material: "Denim",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-jeans-grey-001",
      brand: "H&M",
      cat: "jeans",
      name: "Grey Straight Jeans",
      desc: "Grey washed straight jeans.",
      price: 38.99,
      gender: "UNISEX",
      colors: ["Grey"],
      sizes: ["S", "M"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Straight",
        Style: "Casual",
        Material: "Denim",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-jeans-women-black-001",
      brand: "Zara",
      cat: "jeans",
      name: "Women Black High Jeans",
      desc: "Black high-waist jeans for women.",
      price: 41.99,
      gender: "WOMEN",
      colors: ["Black"],
      sizes: ["XS", "S"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Skinny",
        Style: "Casual",
        Material: "Denim",
        Pattern: "Solid",
      },
    }),

    /* ---------- BOOTS (6) ---------- */
    spec({
      ext: "exp-boot-brown-leather-001",
      brand: "Zara",
      cat: "boots",
      name: "Brown Leather Boots",
      desc: "Brown leather lace-up boots.",
      price: 89.99,
      gender: "MEN",
      colors: ["Brown"],
      sizes: ["41", "42", "43"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Classic",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-boot-black-chelsea-001",
      brand: "H&M",
      cat: "boots",
      name: "Black Chelsea Boots",
      desc: "Black chelsea boots with elastic side.",
      price: 74.99,
      gender: "UNISEX",
      colors: ["Black"],
      sizes: ["40", "41", "42"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Classic",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-boot-women-grey-001",
      brand: "Zara",
      cat: "boots",
      name: "Women Grey Ankle Boots",
      desc: "Grey suede ankle boots for women.",
      price: 79.99,
      gender: "WOMEN",
      colors: ["Grey"],
      sizes: ["39", "40"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-boot-green-001",
      brand: "New Balance",
      cat: "boots",
      name: "Green Outdoor Boots",
      desc: "Green rugged outdoor boots.",
      price: 99.99,
      gender: "MEN",
      colors: ["Green"],
      sizes: ["42", "43", "44"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-boot-red-women-001",
      brand: "Puma",
      cat: "boots",
      name: "Women Red Fashion Boots",
      desc: "Red statement fashion boots.",
      price: 84.99,
      gender: "WOMEN",
      colors: ["Red"],
      sizes: ["39"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Leather",
        Pattern: "Solid",
      },
      oosColors: ["Red"],
    }),
    spec({
      ext: "exp-boot-white-001",
      brand: "Nike",
      cat: "boots",
      name: "White Winter Boots",
      desc: "White insulated winter boots.",
      price: 109.99,
      gender: "UNISEX",
      colors: ["White"],
      sizes: ["43", "44"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),

    /* ---------- LOAFERS (5) ---------- */
    spec({
      ext: "exp-loafer-brown-001",
      brand: "H&M",
      cat: "loafers",
      name: "Brown Suede Loafers",
      desc: "Brown suede penny loafers.",
      price: 64.99,
      gender: "MEN",
      colors: ["Brown"],
      sizes: ["41", "42"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Classic",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-loafer-black-001",
      brand: "Zara",
      cat: "loafers",
      name: "Black Leather Loafers",
      desc: "Polished black leather loafers.",
      price: 69.99,
      gender: "MEN",
      colors: ["Black"],
      sizes: ["42", "43"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Formal",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-loafer-women-white-001",
      brand: "H&M",
      cat: "loafers",
      name: "Women White Loafers",
      desc: "White minimal loafers for women.",
      price: 49.99,
      gender: "WOMEN",
      colors: ["White"],
      sizes: ["39", "40"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-loafer-grey-001",
      brand: "New Balance",
      cat: "loafers",
      name: "Grey Casual Loafers",
      desc: "Grey slip-on casual loafers.",
      price: 54.99,
      gender: "UNISEX",
      colors: ["Grey"],
      sizes: ["41"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-loafer-red-001",
      brand: "Zara",
      cat: "loafers",
      name: "Red Statement Loafers",
      desc: "Red leather statement loafers.",
      price: 74.99,
      gender: "WOMEN",
      colors: ["Red"],
      sizes: ["40"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Classic",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),

    /* ---------- SANDALS (4) ---------- */
    spec({
      ext: "exp-sandal-brown-001",
      brand: "H&M",
      cat: "sandals",
      name: "Brown Leather Sandals",
      desc: "Brown strappy leather sandals.",
      price: 34.99,
      gender: "UNISEX",
      colors: ["Brown"],
      sizes: ["41", "42"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-sandal-black-001",
      brand: "Adidas",
      cat: "sandals",
      name: "Black Sport Sandals",
      desc: "Black adjustable sport sandals.",
      price: 29.99,
      gender: "UNISEX",
      colors: ["Black"],
      sizes: ["42", "43"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-sandal-women-white-001",
      brand: "Zara",
      cat: "sandals",
      name: "Women White Sandals",
      desc: "White flat sandals for women.",
      price: 26.99,
      gender: "WOMEN",
      colors: ["White"],
      sizes: ["39", "40"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Casual",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-sandal-green-001",
      brand: "Puma",
      cat: "sandals",
      name: "Green Pool Sandals",
      desc: "Green slide pool sandals.",
      price: 19.99,
      gender: "UNISEX",
      colors: ["Green"],
      sizes: ["44"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),

    /* ---------- EXTRA SNEAKERS (3) ---------- */
    spec({
      ext: "exp-sneaker-black-001",
      brand: "Nike",
      cat: "sneakers",
      name: "Black Runner Sneaker",
      desc: "Black everyday runner sneaker.",
      price: 94.99,
      gender: "MEN",
      colors: ["Black"],
      sizes: ["42", "43"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Sport",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-sneaker-red-001",
      brand: "Puma",
      cat: "sneakers",
      name: "Red Court Sneaker",
      desc: "Red court-style sneaker.",
      price: 74.99,
      gender: "UNISEX",
      colors: ["Red"],
      sizes: ["41", "42"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Classic",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
    spec({
      ext: "exp-sneaker-women-grey-001",
      brand: "New Balance",
      cat: "sneakers",
      name: "Women Grey Retro Sneaker",
      desc: "Grey retro sneaker for women.",
      price: 84.99,
      gender: "WOMEN",
      colors: ["Grey"],
      sizes: ["39", "40"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Classic",
        Material: "Synthetic",
        Pattern: "Solid",
      },
    }),

    /* ---------- EXTRA FORMAL SHOES (1) ---------- */
    spec({
      ext: "exp-formal-black-oxford-001",
      brand: "Zara",
      cat: "formal-shoes",
      name: "Black Oxford Shoes",
      desc: "Black polished oxford formal shoes.",
      price: 89.99,
      gender: "MEN",
      colors: ["Black"],
      sizes: ["42"],
      attrs: {
        Sleeve: "N/A",
        Collar: "N/A",
        Fit: "Regular",
        Style: "Formal",
        Material: "Leather",
        Pattern: "Solid",
      },
    }),
  ];
