import { writeFileSync } from "node:fs";
import { taxonomyDefinition, taxonomyTrees, type TaxonomyNode } from "../src/lib/catalog/taxonomy/definition";

function slugPart(label: string): string {
  return label
    .toLowerCase()
    .replace(/[-']/g, "")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

const reverseMigration: Record<string, string[]> = {};
for (const [slug, ids] of Object.entries(taxonomyDefinition.migrationMap)) {
  for (const id of ids) (reverseMigration[id] ??= []).push(slug);
}

/* Explicit overrides where the automatic rule is wrong or would target a
   deprecated duplicate. These are the only hand-authored entries. */
const OVERRIDES: Record<string, string> = {
  mens_bottoms_cargo_pants: "cargo",
};

const ROOT_ALIASES: Record<string, string> = {
  womens_lingerie_and_sleepwear: "underwear_and_sleepwear",
};

const canonicalFor = (node: TaxonomyNode): string => {
  const override = OVERRIDES[node.id];
  if (override) return override;
  if (node.parentId === null) {
    return ROOT_ALIASES[node.id] ?? slugPart(node.label);
  }
  const parent = allNodes[node.parentId];
  if (!parent) throw new Error(`missing parent for ${node.id}`);
  const parentCanon = canonicalFor(parent);
  if (node.styleId) return `${parentCanon}::${node.styleId}`;
  const slug = (reverseMigration[node.id] ?? [])[0];
  if (slug) return slug;
  return `${parentCanon}::${slugPart(node.label)}`;
};

const allNodes: Record<string, TaxonomyNode> = {};
for (const g of ["MEN", "WOMEN", "KIDS"] as const) {
  Object.assign(allNodes, taxonomyTrees[g].nodes);
}

const aliases: Record<string, string> = {};
const targets = new Set<string>();
for (const g of ["MEN", "WOMEN", "KIDS"] as const) {
  for (const id of Object.keys(taxonomyTrees[g].nodes)) {
    const target = canonicalFor(taxonomyTrees[g].nodes[id]);
    aliases[id] = target;
    targets.add(target);
  }
}

const sortedAliases = Object.fromEntries(
  Object.entries(aliases).sort(([a], [b]) => a.localeCompare(b))
);
const sortedTargets = [...targets].sort();

const body = `/* AUTO-GENERATED by scripts/gen-taxonomy-aliases.mts - do not edit by hand. */
export const TAXONOMY_ID_ALIASES: Record<string, string> = ${JSON.stringify(sortedAliases, null, 2)};

export const CANONICAL_PLACEMENT_IDS: string[] = ${JSON.stringify(sortedTargets, null, 2)};
`;

const out = "C:/Users/sakhr/Desktop/wearsearch/src/lib/catalog/taxonomy/id-aliases.generated.ts";
writeFileSync(out, body, "utf8");
console.log(`aliases=${Object.keys(sortedAliases).length} targets=${sortedTargets.length}`);
console.log(`sample:`);
for (const id of [
  "mens_bottoms_jeans",
  "mens_bottoms_jeans_skinny",
  "womens_bottoms_jeans_wideleg",
  "kids_bottoms_jeans_and_pants_chinos_and_cargos",
  "womens_shoes_flats_and_sneakers_loafers",
  "mens_bottoms_cargo_pants",
  "womens_lingerie_and_sleepwear",
  "kids_onepieces_kids_dresses",
]) {
  console.log(`  ${id} -> ${aliases[id]}`);
}
