/**
 * Canonical ID compatibility layer.
 *
 * This module lets legacy, path-derived node ids (e.g. `mens_bottoms_jeans`)
 * coexist with the new canonical placement ids (e.g. `jeans`,
 * `jeans::skinny`) that the Unified Canonical Taxonomy will use.
 *
 * Nothing here changes existing behavior: it is a pure resolver. Legacy
 * stored paths (questionnaire sessionStorage, saved state) can be normalized
 * to canonical ids, and canonical ids resolve to themselves, so writes are
 * idempotent.
 *
 * Layer rules:
 *   - A canonical placement id resolves to itself.
 *   - A legacy id resolves to its canonical placement id.
 *   - An unknown id resolves to itself (never throws).
 *
 * The alias table is generated by `scripts/gen-taxonomy-aliases.mts`; Phase 5
 * validation asserts every alias target is a valid canonical id.
 */

import {
  CANONICAL_PLACEMENT_IDS,
  TAXONOMY_ID_ALIASES,
} from "./id-aliases.generated";

/** Version of the taxonomy currently running (legacy trees). */
export const CURRENT_TAXONOMY_VERSION = "2.0.0";

/** Version of the Unified Canonical Taxonomy this layer migrates toward. */
export const CANONICAL_TAXONOMY_VERSION = "3.0.0";

export { CANONICAL_PLACEMENT_IDS, TAXONOMY_ID_ALIASES };

const CANONICAL_SET: ReadonlySet<string> = new Set(CANONICAL_PLACEMENT_IDS);

/** True when `id` is already a canonical placement id. */
export function isCanonicalId(id: string): boolean {
  return CANONICAL_SET.has(id);
}

/**
 * Resolve any id (legacy or canonical) to its canonical placement id.
 * Canonical ids return themselves, making writes idempotent.
 */
export function resolveCanonicalId(id: string): string {
  if (CANONICAL_SET.has(id)) return id;
  return TAXONOMY_ID_ALIASES[id] ?? id;
}

/**
 * Normalize a stored questionnaire path (a chain of ids) to canonical ids.
 * Unknown segments are preserved unchanged so a partially-migrated path
 * never breaks navigation.
 */
export function normalizePath(path: readonly string[]): string[] {
  return path.map((id) => resolveCanonicalId(id));
}
